# Generated by Django 2.0.6 on 2018-07-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('video', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=1000)),
                ('picture', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=20)),
            ],
        ),
    ]
